// src/Utils/Data.js

export const productsList = [
  {
    id: 1,
    name: "Electric Iron",
    category: "home",
    image: require("../assets/products/1.png"),
    price: 1299,
    quantity: "1 unit",
    description: "High quality electric iron with fast heating.",
    nutrition: null,
    rating: 4.3,
  },
  {
    id: 2,
    name: "Safal Sweet Corn",
    category: "fruits",
    image: require("../assets/products/2.png"),
    price: 95,
    quantity: "500 g",
    description: "Fresh frozen sweet corn.",
    nutrition: "Energy 86 kcal",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Maybelline Fit Me Foundation",
    category: "personalCare",
    image: require("../assets/products/3.png"),
    price: 549,
    quantity: "30 ml",
    description: "Lightweight foundation.",
    nutrition: null,
    rating: 4.6,
  },
  {
    id: 4,
    name: "Makeup Palette",
    category: "personalCare",
    image: require("../assets/products/4.png"),
    price: 899,
    quantity: "1 pack",
    description: "Multi-shade makeup palette.",
    nutrition: null,
    rating: 4.4,
  },
  {
    id: 5,
    name: "Coca Cola",
    category: "beverages",
    image: require("../assets/products/5.png"),
    price: 40,
    quantity: "750 ml",
    description: "Refreshing soft drink.",
    nutrition: "Energy 139 kcal",
    rating: 4.2,
  },
  {
    id: 6,
    name: "Organic Wheat",
    category: "grocery",
    image: require("../assets/products/6.png"),
    price: 399,
    quantity: "5 kg",
    description: "100% organic wheat grains.",
    nutrition: "Protein 13g",
    rating: 4.7,
  },
  {
    id: 7,
    name: "Homelite Bread",
    category: "bakery",
    image: require("../assets/products/7.png"),
    price: 45,
    quantity: "400 g",
    description: "Soft and fresh bread.",
    nutrition: "Energy 265 kcal",
    rating: 4.1,
  },
  {
    id: 8,
    name: "Chocolate Ice Cream",
    category: "frozen",
    image: require("../assets/products/8.png"),
    price: 120,
    quantity: "1 pc",
    description: "Creamy chocolate ice cream.",
    nutrition: "Energy 207 kcal",
    rating: 4.8,
  },
  {
    id: 9,
    name: "Organic Desi Cow Ghee",
    category: "dairy",
    image: require("../assets/products/9.png"),
    price: 699,
    quantity: "500 ml",
    description: "Pure desi cow ghee.",
    nutrition: "Fat 100g",
    rating: 4.9,
  },
  {
    id: 10,
    name: "Sourdough Bread",
    category: "bakery",
    image: require("../assets/products/10.png"),
    price: 80,
    quantity: "1 loaf",
    description: "Naturally fermented bread.",
    nutrition: "Energy 289 kcal",
    rating: 4.4,
  },
  {
    id: 11,
    name: "Whole Farm Dal",
    category: "grocery",
    image: require("../assets/products/11.png"),
    price: 189,
    quantity: "1 kg",
    description: "Protein-rich whole farm dal.",
    nutrition: "Protein 24g",
    rating: 4.6,
  },
  {
    id: 12,
    name: "Huggies Diapers",
    category: "baby",
    image: require("../assets/products/12.png"),
    price: 999,
    quantity: "32 pcs",
    description: "Soft baby diapers.",
    nutrition: null,
    rating: 4.5,
  },
  {
    id: 13,
    name: "Toy Monster Truck",
    category: "toys",
    image: require("../assets/products/13.png"),
    price: 499,
    quantity: "1 unit",
    description: "Durable toy monster truck.",
    nutrition: null,
    rating: 4.3,
  },
  {
    id: 14,
    name: "Fortune Soybean Oil",
    category: "grocery",
    image: require("../assets/products/14.png"),
    price: 179,
    quantity: "1 L",
    description: "Refined soybean oil.",
    nutrition: "Fat 100g",
    rating: 4.2,
  },
  {
    id: 15,
    name: "LED Bulb",
    category: "home",
    image: require("../assets/products/15.png"),
    price: 149,
    quantity: "9 W",
    description: "Energy efficient LED bulb.",
    nutrition: null,
    rating: 4.4,
  },
  {
    id: 16,
    name: "McCain Smiles",
    category: "frozen",
    image: require("../assets/products/16.png"),
    price: 249,
    quantity: "750 g",
    description: "Crispy potato smiles.",
    nutrition: "Energy 150 kcal",
    rating: 4.7,
  },
];
